$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue #example-deployment
endpoint_name: example-endpoint
model:
  path: /Users/anastasiastefanescu/Documents/code-stats/services/azure-example/model
code_configuration:
  code: /Users/anastasiastefanescu/Documents/code-stats/services/azure-example/scoring
  scoring_script: score.py
environment: 
  conda_file: /Users/anastasiastefanescu/Documents/code-stats/services/azure-example/conda.yaml
  image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest
instance_type: Standard_DS3_v2
instance_count: 1
